# Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn; seaborn.set()

# Introduction

- Pandas is a newer package built on top of NumPy, and provides an efficient implementation of a DataFrame.
- DataFrames are essentially multidimensional arrays with attached row and column labels, and often with heterogeneous types and/or missing data.

# Introducing Pandas Objects

## The Pandas Series Object

### Introduction

- A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows.

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
# values is simply a NumPy array
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

np.float64(0.5)

In [6]:
data[1::2]

1    0.5
3    1.0
dtype: float64

### Series as generalized NumPy array

- While the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values
- This explicit index definition gives the Series object additional capabilities.
- The index need not be an integer, but can consist of values of any desired type. 

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data['b']

np.float64(0.5)

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [10]:
data[5]

np.float64(0.5)

### Series as specialized dictionary

In [11]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

- By default, a Series will be created where the index is drawn from the sorted keys.

In [12]:
population.values

array([38332521, 26448193, 19651127, 19552860, 12882135])

In [13]:
population.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [14]:
# Slicing can also be done unlike dictionaries
population['Texas':]

Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135
dtype: int64

In [15]:
population[:'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [16]:
population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

### Constructing Series objects

In [17]:
# data can be a scalar, which is repeated to fill the specified index
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [18]:
# data can be a dictionary, in which index defaults to the sorted dictionary keys
data = pd.Series({2:'a', 1:'b', 3:'c'})
data

2    a
1    b
3    c
dtype: object

In [19]:
# the Series is populated only with the explicitly identified keys
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

## The Pandas DataFrame Object

### DataFrame as a generalized NumPy array

- If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names.
- Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a DataFrame as a sequence of aligned Series objects.
- Here, by "aligned" we mean that they share the same index.

In [20]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [21]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [22]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [23]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [24]:
states.columns

Index(['population', 'area'], dtype='object')

- Thus the DataFrame can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.

### DataFrame as specialized dictionary

- Similarly, we can also think of a DataFrame as a specialization of a dictionary.
- Where a dictionary maps a key to a value, a DataFrame maps a column name to a Series of column data. 

In [25]:
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [26]:
states["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Constructing DataFrame objects

#### From a single Series object

In [27]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [28]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#### From a list of dicts

In [29]:
data = [ {"a": i ** 2 + 1, "b": 2 ** i} for i in range(3) ]
data

[{'a': 1, 'b': 1}, {'a': 2, 'b': 2}, {'a': 5, 'b': 4}]

In [30]:
pd.DataFrame(data)

a  b
0  1  1
1  2  2
2  5  4

- Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e., "not a number") values.

In [31]:
data = [{'a': 1, 'b': 2}, {'b': 3, 'c': 4}]
data

[{'a': 1, 'b': 2}, {'b': 3, 'c': 4}]

In [32]:
pd.DataFrame(data)

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### From a dictionary of Series objects

In [33]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [34]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [35]:
pd.DataFrame({"population": population, "area": area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### From a dict of dicts

In [36]:
# It is like a dictionary of series objects (as each Series
# can be represented by a dictionary
pd.DataFrame({
    "col1": {"a" : 4, "b": 5, "c": 3},
    "col2": {"a" : 4, "b": 5, "d": -1}
})

col1  col2
a   4.0   4.0
b   5.0   5.0
c   3.0   NaN
d   NaN  -1.0

#### From a 2D NumPy Array

In [37]:
data = np.random.rand(3, 2)
data

array([[0.25381026, 0.8125196 ],
       [0.49752941, 0.69773924],
       [0.63952443, 0.37558757]])

In [38]:
pd.DataFrame(data, columns=["foo", "bar"], index=["a", "b", "c"])

foo       bar
a  0.253810  0.812520
b  0.497529  0.697739
c  0.639524  0.375588

#### From a NumPy Structured Array

In [39]:
data = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
data["A"] = [3, 5, -12]
data["B"] = [0., -3.14, 3.14]
data

array([(  3,  0.  ), (  5, -3.14), (-12,  3.14)],
      dtype=[('A', '<i8'), ('B', '<f8')])

In [40]:
pd.DataFrame(data)

A     B
0   3  0.00
1   5 -3.14
2 -12  3.14

## The Pandas Index Object

### Introduction

In [41]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

### Index as immutable array

In [42]:
ind[1]

np.int64(3)

In [43]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [44]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


- One difference between Index objects and NumPy arrays is that indices are immutable–that is, they cannot be modified via the normal means

In [45]:
try:
    ind[1] = 0
except TypeError as e:
    print("Error in assignment")
    print(e)

Error in assignment
Index does not support mutable operations


- This immutability makes it safer to share indices between multiple DataFrames and arrays, without the potential for side effects from inadvertent index modification.

### Index as ordered set

- The Index object follows many of the conventions used by Python's built-in set data structure
- Unions, intersections, differences, and other combinations can be computed in a familiar way

In [54]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [55]:
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

In [56]:
indA.union(indB)

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [57]:
indA.symmetric_difference(indB)

Index([1, 2, 9, 11], dtype='int64')